name: news-parser

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  parse-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        working-directory: ./src
        env:
          SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_TABLE_NAME: ${{ secrets.SUPABASE_TABLE_NAME }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_DEBUG_BOT_TOKEN: ${{ secrets.TELEGRAM_DEBUG_BOT_TOKEN }}
          TELEGRAM_DEBUG_CHAT_ID: ${{ secrets.TELEGRAM_DEBUG_CHAT_ID }}
        run: php -f index.php || exit 1